sudo: required

services:
  - docker
  
language: go

go:
    - "1.10"

deploy:
  provider: gae
  keyfile: "go-vim-ee18aba1914a.json"
  project: "go-vim"
  skip_cleanup: true
  verbosity: debug
  on: master
    
before_install:
  - openssl aes-256-cbc -K $encrypted_97f24f268f56_key -iv $encrypted_97f24f268f56_iv -in go-vim-ee18aba1914a.json.enc -out go-vim-ee18aba1914a.json -d
