sudo: false
language: go
go:
- 1.10.x
- 1.x
git:
  depth: 1
notifications:
  email: false
deploy:
  provider: gae
  keyfile: go-vim-7f66f14276aa.json 
  project: go-vim
  skip_cleanup: true
  verbosity: debug
  on: master
before_install:
- openssl aes-256-cbc -K $encrypted_97f24f268f56_key -iv $encrypted_97f24f268f56_iv
  -in go-vim-7f66f14276aa.json.enc -out go-vim-7f66f14276aa.json -d
