runtime: go112

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /static
  static_dir: static
- url: /(|compile|fmt|share)
  script: auto
- url: /p/.+
  script: auto
